# Generated by Django 4.0.5 on 2022-06-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('branch_subject', models.CharField(max_length=50)),
                ('specific_subject', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('First', 1), ('Second', 2), ('Third', 3), ('Fourth', 4)], default='First', max_length=10)),
                ('link', models.URLField()),
            ],
        ),
    ]
