# Generated by Django 4.0.5 on 2022-06-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.CharField(choices=[('First', 1), ('Second', 2), ('Third', 3), ('Fourth', 4), ('Fifth', 5), ('Sixth', 6)], default='First', max_length=10),
        ),
    ]
