# Generated by Django 4.0.5 on 2022-06-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='relevancy',
            field=models.FloatField(default=0),
        ),
    ]
