# Generated by Django 4.0.5 on 2022-06-26 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkmanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works', models.IntegerField(default=0)),
                ('workxp', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('raiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_raiser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('workxp', models.IntegerField(default=0)),
                ('completor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
